
#ifndef MKL46Z4_PROJECT_WORK_SOURCE_MKL46Z4_PROJECT_WORK_HPP
#define MKL46Z4_PROJECT_WORK_SOURCE_MKL46Z4_PROJECT_WORK_HPP

#include "cmsis_compiler.h"
#include "cstdint"
#include "bitManipulation.hpp"

#endif // MKL46Z4_PROJECT_WORK_SOURCE_MKL46Z4_PROJECT_WORK_HPP
